#! package-manifest: deploy/catalog_resources/community/0.0.2/inferator-operator.0.0.2.clusterserviceversion.yaml
channels:
- currentCSV: inferator-operator.0.0.2
  name: alpha
packageName: inferator-operator
