apiVersion: rule.example.com/v1alpha1
kind: OperationRule
metadata:
  name: example-operationrule
spec:
  expose: true
  resources:
    deployment1:
      apiVersion: apps/v1
      kind: Deployment
      name: testapp1
    deployment2:
      apiVersion: apps/v1
      kind: Deployment
      name: testapp2
    deployment3:
      apiVersion: apps/v1
      kind: Deployment
      name: testapp3
  inference:
    inputs:
    - deployment1
    rules:
    - when:
      - '$deployment1.spec.replicas >= 3'
      then:
      - name: deployment2
        path: spec
        value:
          replicas: '$deployment1.spec.replicas / 2 + 1'
      - name: deployment3
        path: metadata.labels
        value:
          example: '$deployment1.metadata.name'
      - name: deployment3
        path: spec
        value:
          replicas: '1'
    - when:
      - '$deployment1.spec.replicas < 3'
      then:
      - name: deployment2
        path: spec
        value:
          replicas: '1'
      - name: deployment3
        path: spec
        value:
          replicas: '0'
