apiVersion: apps/v1
kind: Deployment
metadata:
  name: inferator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: inferator
  template:
    metadata:
      labels:
        name: inferator
    spec:
      serviceAccountName: inferator
      containers:
        - name: inferator
          # Replace this with the built image name
          image: REPLACE_IMAGE
          command:
          - inferator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "inferator"
