apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: inferator
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - apps
  resources:
  - deployments/finalizers
  verbs:
  - update
- apiGroups:
  - rule.example.com
  resources:
  - operationrules
  - operationrules/finalizers
  verbs:
  - '*'
